### ISSUE TITLE
Wrapper library for Python already on Github

### ISSUE THREAD

**Issue by nbro** [wjoye/tktable#1]
Two years ago I decided to make the [`tktable`'s wrapper library for Python available on Github](https://github.com/nbro/tktable/commits/master) with the intent of increase its visibility, but now, since you have uploaded the original Tcl/Tk extension, I'm not sure anymore that was a good idea. 

Over the years Python users have had many problems with the wrapper library, because many times the original Tcl/Tk extension is not installed on their system yet. There's no automatic and standardized way of installing this extension in the 3 major OS platforms, for all distributions. See for example this issue: [https://github.com/nbro/tktable/issues/1](https://github.com/nbro/tktable/issues/1).

For some Ubuntu distributions, you can simply do `sudo apt-get install tk-table`, but it may not work for all Ubuntu distributions. On Mac, you may be able to install it through MacPorts, but I'm not sure how reliable it is. On Windows probably the only way to install `tktable` is to use the package manager of ActiveState's ActiveTcl, which means you need also to install this latter.

I would like to note that the wrapper library I'm "maintaining" has already a few _little_ modifications with respect to the Python wrapper you have in this repository under [`library/`](https://github.com/wjoye/tktable/blob/master/library/tktable.py).

That's why I also wanted to create an automatic way for Python users to install the wrapper library by simply using Python's package manager `pip`, but to do that I needed first a way to install this original library, but I'm not qualified enough for now to do it.

So the reason I opened this issue is to understand which plans do you have for the future regarding this library.

**Comment by wjoye** [comment]
Nelson

Thanks for the note. My only purpose of my GitHub repo ofTkTable, is to support my main project, SAOImage DS9. I needed TkTable up to date with TEA 3.10 support. The result of the this is that I can build under all versions of Linux, MacOSX, and Windows, both standard LIBS (*.a) and shared LIBS (*.dylib, *.so). (I’ve not tried a DLL under windows yet, I should make sure this works)

I have no other plans (enhancements, etc) other to see that I can build under my supported platforms. I’ve made no other modifications other than TEA 3.10 support.

As far as I can tell, TkTable has been orphaned. (unlike TkImag which just received a much needed update).

Regards

bill joye

**Comment by priyanka22kar** [comment]
help me with the installation steps 
I want to use it for viewing my mongodb tables and modifying it using tkinter window 
I hope that is possible 
@nbro @wjoye 
thank you

**Comment by wjoye** [comment]
To build TkTable:

install tcl/tk devel if needed
download the source

% cd tktable
% ./configure
% make install

**Comment by priyanka22kar** [comment]
@Whoye thank you for your response
I already have tcl/tk
I wanted to know further steps of installation
Your help would be appreciated.
